 - apiVersion: v1
  kind: Namespace
  metadata:
    name: default-1735556045877
  spec:
    finalizers:
      - kubernetes
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: pbkimagepbkdeploy
    namespace: default-1735556045877
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: pbkimagepbkdeploy
    template:
      metadata:
        labels:
          app: pbkimagepbkdeploy
      spec:
        nodeSelector:
          kubernetes.io/os: linux
        containers:
          - name: pbkimagepbkdeploy
            image: pbkregistrypbk.azurecr.io/pbkimagepbk:v1
            ports:
              - containerPort: 80
            resources:
              requests:
                cpu: '2'
                memory: 12G
              limits:
                cpu: '256'
                memory: 11400G
- apiVersion: v1
  kind: Service
  metadata:
    name: pbkimagepbk-service
    namespace: default-1735556045877
  spec:
    type: LoadBalancer
    ports:
      - targetPort: 80
        name: port80
        port: 80
        protocol: TCP
    selector:
      app: pbkimagepbkdeploy
