name: Azure Container Instance

on:
  push

env:
  AZURE_RESOURCE_GROUP : test-acr-rg
  AZURE_ACR_NAME : pbkregistrypbk

jobs:
  azuread:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Microsoft Azure
      run: |
        az login --service-principal --tenant ${{ secrets.AZURE_TENANT_ID}} --username ${{ secrets.AZURE_CLIENT_ID}} --password ${{ secrets.AZURE_SECRET_ID}}
    - name: Create Azure Container Registry
      run: |
        az acr create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name ${{ env.AZURE_ACR_NAME }} --sku Basic
    - name: Authenticate to ACR
      run: |
        az acr login --name ${{ env.AZURE_ACR_NAME }}
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ env.AZURE_ACR_NAME }}.azurecr.io/pbkimagepbk:v1
    - name: Create Azure Kubernetes service
      run: |
        az aks create --resource-group ${{ env.AZURE_RESOURCE_GROUP }} --name pbkakspbk --location australiaeast --attach-acr pbkregistrypbk --generate-ssh-keys
